---
- name: Set up the environment. Ensure that python3, docker, and docker-compose are installed.
  hosts: web
  remote_user: root
  vars:
    venv: ~/iuht/.venv
  tasks:
    - name: Get the local git repository version
      local_action: command git describe --dirty --always
      register: git_version

    - name: Install Python 3.6
      yum: name=python36
      become: yes

    - name: Install Docker
      yum: name=docker
      become: yes

    - name: Create Virtual Environment if it doesn't exist
      command: virtualenv --python=python3 {{ venv }}
      args:
        creates: "{{ venv }}"

    - name: Install Docker-Compose in the Virtual Environment
      pip: name=docker-compose virtualenv={{ venv }}

    - name: Ensure that Docker is running
      service: name=docker state=started
      become: yes

    - name: Add ansible user to the docker group
      user: name="{{ansible_user}}" groups=docker append=yes
      become: yes

    - name: Reset ssh connection
      meta: reset_connection

- name: Copy Distribution to the remote
  hosts: web
  remote_user: root
  become: yes
  tasks:
    - name: Ensure that the directory /opt/iuht/ exists
      file:
        path: /opt/iuht
        state: directory

    - name: Copy Heritage Trail Distribution to the remote host if it doesn't exist
      unarchive:
        src: ../build/docker/distributions/iuht-{{ git_version.stdout }}.tar
        dest: /opt/iuht/
        creates: /opt/iuht/iuht-{{ git_version.stdout }}

- name: Run docker containers
  hosts: web
  remote_user: root
  vars:
    docker_dir: /opt/iuht/iuht-{{ git_version.stdout }}/docker/iuht
    venv: ~/iuht/.venv
  tasks:
    - name: Increase the Virtual Memory limit for elasticsearch
      shell: sysctl -w vm.max_map_count=262144
      become: yes

    - name: Run docker-compose command to start docker containers
      command: "{{ venv }}/bin/docker-compose -f ./docker-compose.yml -f ./mixins/clash.yml up --build -d"
      args:
        chdir: "{{ docker_dir }}"